### ISSUE TITLE
Benchmark/Understand threading on single node

### ISSUE THREAD

**Issue by ilectra** [UCL-ARC/Grid#10]
See how timing scales for various numbers of OpenMP threads, sizes of grid, and pinning flags.

**DONE:**
- [x] Table of results from @asifsamiarain 's experiments a-d.
- [x] Recommendation of OpenMP flags

**Comment by asifsamiarain** [comment]
In connection with the experimental build `/home/dp208/dp208/shared/RAC16/pgda001/gd_tursa-gnu_seq-001_sp2n_def00` ran benchmarking tests on single node of Tursa's CPU partition having short time steps settings such as sp2n's MDsteps=2 & trajL=0.1.

Here is below the output of `lscpu`:

![Image](https://github.com/user-attachments/assets/826af573-da45-4239-a88d-0e4ced3f6062)


Here are below the results:

![Image](https://github.com/user-attachments/assets/b0c7344e-f232-428b-8b0e-1bc3a72f315a)

By looking at the results we may say the OMP flags do improve results with higher threads while most optimum results are achievable with 2, 4, 8 threads for smaller Grids and 16 for higher Grids.

**Comment by ilectra** [comment]
@asifsamiarain has repeated the above study for the `48.48.48.48` grid with hyperthreading disabled, and scaling looks better and more stable even without pinning. He will re-do it for all grid sizes and will add a table like the above for the case of disabled hyperthreading. This should also become part of our default settings for benchmarking.

**Comment by asifsamiarain** [comment]
As we may see above in the output of lscpu, at Tursa's cpu partition two threads per core setting is activated by default so via sbatch flag `--threads-per-core=1` disabled the setting, repeated above tests and here are below the results:

![Image](https://github.com/user-attachments/assets/257efdf8-120f-4e20-a677-c569759c5c89)

**Comment by ilectra** [comment]
Some conclusions: 
- For one MPI process, we don't want to use more than 16 threads (threading almost scales to 32 for only the larger grids)
- For grids larger than 32^4, we want to try 2 or more MPI ranks in the future
- In the future, we should increase the grid one dimension at a time, for a proper x2 increase in load (currently it's x16)
